### ISSUE TITLE
Unexpected result when running a command included a binding key

### ISSUE THREAD

**Issue by lvarayut** [kana/vim-arpeggio#12]
Let's say I have bound the `tr` to be expanded as `true`:

```sh
Arpeggio inoremap tr true
```

Then, I run command `:normal i'use strict'`, the result shown as `use strueict`. Is there any workaround to solve this problem?

**Comment by kana** [comment]
Use `:normal!` instead of `:normal`.

**Comment by lvarayut** [comment]
Thanks for your help. It worked perfectly.
