### ISSUE TITLE
mapping <bar>

### ISSUE THREAD

**Issue by nilsbecker** [kana/vim-arpeggio#14]
i have been trying to map the sequence `{|`. vim help says that the pipe character has to be escaped but none of the options worked for me?!

**Comment by kana** [comment]
Thank you for the report. I've never used such a unique key combination… and I've confirmed that there is a problem to define intermediate mappings with `<Bar>`.  I'll try to fix it later.

**Comment by kana** [comment]
I've fixed the bug.  Please try the latest version.  Note that you have to write `<Bar>` to express `|`.  For example, `:Arpeggio map }<Bar> foo`.

**Comment by nilsbecker** [comment]
thanks for the quick response. unfortunately it is not quite working for me yet. i do
```
Arpeggio imap <buffer> {<bar> test
```
but i then get the info `<Bar> already mapped in mode i` ? i i type `imap <bar>` i get something containing `@<SNR>30_chord_key('|')`

**Comment by nilsbecker** [comment]
however, before i try to define the arpeggio mapping, i get `no mapping found` when i ask `imap <bar>`...

**Comment by kana** [comment]
I've tried reproducing that problem with the following steps:

```
git clone https://github.com/kana/vim-arpeggio.git
cd ./vim-arpeggio
vim -N -u NONE -i NONE --cmd "set rtp^=$PWD | runtime plugin/arpeggio.vim | Arpeggio inoremap }<Bar> xyz"
# Then type `}` and `|` simultaneously in Insert mode.  `xyz` will be inserted instead.
```

But I couldn't reproduce that problem.  It seems to be caused by your configuration.

**Comment by nilsbecker** [comment]
i can confirm that your repro case works here as well. something else must be interacting with it badly...

**Comment by nilsbecker** [comment]
i tried around a bit and i find that i cannot map `{<bar>` this way. is this expected?

**Comment by kana** [comment]
> actually i can map it but it does not work afterwards...

Hmm? Please describe the situation precisely. Does it mean that no error happens to define `Arpeggio inoremap {<Bar> xyz`? If so, what happens when you simultaneously type `{` and `|` in Insert mode? 

There is no restriction on key combinations to define key mappings with vim-arpeggio.  So that the problem might be caused by your keyboard or something else…

**Comment by nilsbecker** [comment]
it's macvim on a mac so it might be that that has something to do with it. 

i now tried again. in fact on one machine i get no error on defining the mapping but the mapping does not actually get applied (i get `{` and `|` inserted as characters). 

on the other machine the mapping does work. curious. it seems this is a mac specific thing.

**Comment by nilsbecker** [comment]
i tried a third machine, another macbook pro, and on that machine, your minimal example again works. both with `{` and `}`. not sure if this can be solved easily as it seems to be caused by system configuration details.

**Comment by nilsbecker** [comment]
i had a look at this once more. indeed it is a keyboard limitation.

on some keyboards (on apple macs, all in US english layout), the key `{` cannot be pressed simultaneously with `|`. what i mean is that of course you can press them simultaneously but only `|`  will be transferred to the operating system. there is a set of keys on the keyboard that will not get transmitted when pressed together with `|`. besides `{` this set includes also `+` and maybe more. . this is a non-vim issue.

the set does not include `}`, so i used that to define an arpeggio mapping. this works fine. however, i get error messages when i re-define the same mapping. since i have the mapping inside an autocommand for a FileType, re-definition happens e.g. when i reload the file with `:e!`.  the error message i get is the one reported earlier, `<Bar> already mapped in mode i`.

i still think this is a bug in vim-arpeggio: re-defining the same mapping should not raise a warning. 

my current workaround is this:
```
  au FileType ocaml silent! Arpeggio iunmap <buffer> }<bar> 
  au FileType ocaml Arpeggio imap <buffer> }<bar> ∔∔ 
```

**Comment by kana** [comment]
The error message you saw should not be reported for that case.  It seems to be an error to define arpeggio key mappings which contains `<Bar>`.  I'll investigate the problem later.

**Comment by kana** [comment]
vim-arpeggio defines many intermediate key mappings to recognize what keys are simultaneously pressed.  If non-arpeggio key mappings are already defined, the `xxx already mapped in mode xxx` message will be shown to notice that some keys are unexpectedly overridden.

But vim-arpeggio sometimes fails to recognize whether a key is a part of arpeggio key mapping or not.  One of the problematic keys is `|`.  I'll fix the bug later.

**Comment by kana** [comment]
I've pushed a fix: https://github.com/kana/vim-arpeggio/commit/d24b6ff9f796ea604aa0939ba67bce739de72830  Please try the latest version.

**Comment by nilsbecker** [comment]
this seems to work on initial testing. thanks! i'll report again if something goes wrong but for now it seems solved!
