### ISSUE TITLE
Documentation for Vim8 Packages Sourcing Order

### ISSUE THREAD

**Issue by tessarin** [kana/vim-arpeggio#15]
Vim only adds package paths to `'runtimepath'` after loading the  _.vimrc_,  making  the  traditional  autoload  mechanic unusable  for  this  particular  case.  If  the  plugin  was installed in a package, using `arpeggio#load()` as mentioned in the documentation does not work anymore.

One way to add the plugin directory to `'rtp'` is:

```vim
packadd! vim-arpeggio
call arpeggio#load()
```

Or simply source it all which dismisses the autoload function call:

```vim
packadd vim-arpeggio
```

I think it would be  useful to have this information updated in  the documentation  or  install  instructions. Issue  #11 might be related to this.

**Comment by kana** [comment]
Thank you for the report. I'll update the document soon.
