### ISSUE TITLE
Is it possible to follow an arpeggio with a simple keybinding or another arpeggio?

### ISSUE THREAD

**Issue by blasco** [kana/vim-arpeggio#18]
First of all, thank you for the great idea and implementation. This already speeds up my workflow by 100%. I would like to know if it would be possible to go a little bit further or to brainstorm how we could achieve so. I would like to combine sequences, just like in normal vim, if I have the following mappings:

```
nmap xa :DoA
nmap xb :DoB
```

When I press "x", vim waits for me to press "a" or "b". I would like to achieve similar behavior but with arpeggios, conceptually something like this:

```
nmap Arpeggio(<leader>,x)a :DoA
nmap Arpeggio(<leader>,x)b :DoB
```

Now I would do a `<leader>+x` arpeggio, and vim would wait for "a" or "b". 
This would speed up lots of <leader> commands. Going even further, it would be interesting to sequence also with other arpeggios. What do you think? Is this maybe already achievable?

**Comment by kana** [comment]
Hmm, that sounds interesting. It's possible to define arpeggio key mappings followed by non-arpeggio key mappings. For example:

```vim
Arpeggio nmap jk <Plug>(jk)
nnoremap <Plug>(jk)a :echo "AAA"<CR>
nnoremap <Plug>(jk)b :echo "BBB"<CR>
```

It might be possible define arpeggio key mappings followed by other arpeggio key mappings, like pressing A and B then pressing C and D.  But such configuration requires tons of intermediate key mappings, and it seems to be hard to generalize how to generate them.

**Comment by blasco** [comment]
Thanks a lot, arpeggio key mappings followed by non arpeggio key mappings is already a huge improvement to my workflow, I will be able to combine and generalize a lot of <leader> commands. 

Arpeggio followed by arpeggio could also be interesting, but if it is too difficult to generalize it can definitely wait. Even if it might require a lot of intermediate mappings it might be interesting to have one example, just in case it is really worth it for a particular case. If you could craft such example it would be great, but if its too much don't bother, I personally don't need that, at least for now. Maybe someone might ask in the future.
