### ISSUE TITLE
leader mapping generates a warning

### ISSUE THREAD

**Issue by blasco** [kana/vim-arpeggio#19]
If I set the following mappings:

```
exec "Arpeggio nmap ar :Fun1<CR>
exec "Arpeggio nmap ao :Fun2<CR>
```
It works as expected, but if I use <leader> intead:
```
exec "Arpeggio nmap <leader>r :Fun1<CR>
exec "Arpeggio nmap <leader>o :Fun2<CR>
```
I get  when entering vim from the terminal:
```
Key '<leader>' is already mapped in mode 'n'
```
Although it works as expected. 
Is there a way to hide this warning?

**Comment by kana** [comment]
Use `silent`. For example:

```vim
silent Arpeggio nmap <leader>r :Fun1<CR>
```

But I recommend to check your configuration, especially before the arpeggio mappings. The warning means that

- You defined something like `nmap <leader> :Foo<CR>` before the arpeggio mappings, and
- The non-arpeggio mapping is overridden to define the arpeggio mappings.

Since vim-arpeggio defines tons of internal key mappings, it's easy to break user's configuration.  That's why vim-arpeggio shows that warning.

**Comment by blasco** [comment]
Quite strange, I've checked and I don't have that mapping defined. Maybe another plugin is using that, I'll need to figure out which. I've checked the output of `:map <leader>` and this is the only thing I have that looks suspicious:

```
s  <Space>     * <C-O>"_c<Space>
   <Space><Space>   <Plug>(easymotion-prefix)
```

My leader key is `<space>`. Could that be breaking it?

**Comment by kana** [comment]
To avoid misunderstanding, would you mind pasting the followings?

- actual warning message you saw, and
- actual commands to define arpeggio mappings that cause the warning

```
s  <Space>     * <C-O>"_c<Space>
```

This looks suspicious, but its mode doesn’t match to the warning message in the first comment.

**Comment by blasco** [comment]
actual warning message you saw:
```
Key '<leader>' is already mapped in mode 'n
```
actual commands to define arpeggio mappings that cause the warning:

Interesting enough, this doesn't cause it:
```
Arpeggio nmap <leader>e <Plug>(edit)
" <leader>+er:= edit recent
nnoremap <Plug>(edit)r :CtrlPMRUFiles<CR>
" <leader>+ef:= edit file in project
nnoremap <Plug>(edit)f :CtrlP<CR>
```
But these ones do trigger that message:

```
Arpeggio nmap <leader>f <Plug>(find)
nmap     <Plug>(find)f <Plug>CtrlSFPrompt
vmap     <Plug>(find)f <Plug>CtrlSFVwordPath
vmap     <Plug>(find)F <Plug>CtrlSFVwordExec
" Search word under cursor
nmap     <Plug>(find)w <Plug>CtrlSFCwordPath
" Search last  searched pattern
nmap     <Plug>(find)s <Plug>CtrlSFPwordPath
nnoremap <Plug>(find)t :CtrlSFToggle<CR>
```

**Comment by kana** [comment]
Hmm, that's strange.  None of your own key mappings are overridden by vim-arpeggio.  So that it seems to be a bug of vim-arpeggio which shows a false warning.  I'll investigate it later.

**Comment by kana** [comment]
I've fixed the bug.  Try the latest version.
