### ISSUE TITLE
Interfering with coc autocompletion

### ISSUE THREAD

**Issue by blasco** [kana/vim-arpeggio#24]
I've been experiencing problems with the following plugin:

https://github.com/neoclide/coc.nvim

In particular using the ts-server

https://github.com/neoclide/coc-tsserver/issues/84

The main issue was that suggestion boxes with errors and warnings would end up creating a buffer that would interfere with saving, so I couldn't `:wa`. I did not know what was causing it, but after disabling the plugins I ended narrowing it down to vim-arpeggio. I'm not sure if it is the real cause, do you have any suggestion how could I further debug it or if there is something in vim-arpeggio that could be causing the issue?

**Comment by kana** [comment]
I took a quick look on coc.nvim, but it's too large to guess what's wrong with vim-arpeggio…

Try minimizing configuration and steps to reproduce the problem, since it's impossible for others to reproduce the problem with your description.
