### ISSUE TITLE
recursive map to another arpeggio sequence?

### ISSUE THREAD

**Issue by BertrandSim** [kana/vim-arpeggio#25]
Hi, this is more of a feature request / question. 

Is it possible to `:Arpeggio map` a key-chord to another key-chord?
As a minimal example, if I have the following:
```
Arpeggio iremap jk ()
Arpeggio inoremap () ()<C-G>U<Left> 
```
then I hope that pressing jk will insert a pair of `()` with cursor in between. (I made up the command 'iremap', for illustration purposes)

I read about `Arpeggionoremap` in the help. But as I understand it, that seems to be for recursive mappings of individual keystrokes, not for key-chords?

* * *

For now, it seems that a workaround is 
```
Arpeggio imap jk <Plug>(parens)
Arpeggio imap () <Plug>(parens)
inoremap <Plug>(parens) ()<C-G>U<Left>
```

I would like to know if there is a better way to achieve this?

**Comment by kana** [comment]
If I understand correctly, you want to use both `jk` and `()` to do `()<C-G>U<Left>`, don't you?

In that case, use `imap` instead of `iremap`. (`iremap` is not a valid command.  So your first example does nothing about `jk`.)

```vim
Arpeggio imap jk ()
Arpeggio inoremap () ()<C-G>U<Left> 
```

This should work as you expected.

**Comment by BertrandSim** [comment]
Thank you for the reply.
Indeed, I want to use both `jk` and `()` to achieve the same effect.

Before I posted this request, I tried your solution above, but that didn't work.
It turns out that another plugin (autopairs) had mapped `(` and `)`.
After unmapping `(` and `)`, your solution worked as expected :)
