### ISSUE TITLE
undo joining

### ISSUE THREAD

**Issue by nilsbecker** [kana/vim-arpeggio#34]
i'm trying to undo an arpeggio map in one step. normally this works, i.e. `Arpeggio imap jk asdf` will undo in one step. however, my map uses the expression register to call a function:
```
Arpeggio inoremap () ()<c-r>=UltiSnips#Expand()<cr>
```
this is useful for me as an auto-parentheses function in conjunction with a snippet that expands `()` in UltiSnips. See also [this stackoverflow question](https://vi.stackexchange.com/questions/39575/undo-joining-a-mapping-that-uses-the-expression-register). 

when i undo after this mapping, the initial `()` is still present; i have to undo again to make it disappear. how can i undo the full mapping in one go?

**Comment by kana** [comment]
At least, arpeggio is not relevant to the problem.  Because it can be reproduced without arpeggio.  For example, changing the key mapping to expand the snippet as follows:

```vim
inoremap () ()<c-r>=UltiSnips#ExpandSnippet()<cr>
```

still needs undo twice.

**Comment by nilsbecker** [comment]
ah thanks, that's good to know. i guess we can close this then?

**Comment by nilsbecker** [comment]
i'll update the SO question as well
